server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goTestDemo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Aa123456

mybatis:
  type-aliases-package: deadline.user.pojo




