server:
  port: 8088
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087  /eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
# 服务消费方要拉取服务列表，对应着拉取周期